version: "3.9"

services:
  churras:
    build: .
    container_name: churras_app    
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app/churras
    links:
      - db
    depends_on:
      - db

  db:
    container_name: churras_db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=kevinpagliuca
      - POSTGRES_PASSWORD=kevindocker
      - POSTGRES_DB=churrasdocker
    volumes:
      - pgdata:/data/postgres  
    
volumes:
  pgdata:
    driver: local